### ISSUE TITLE
License for commercial use

### ISSUE THREAD

**Issue by andreishappy** [dm3ll3n/ShinyStudio#10]
Hi 👋 

We're currently looking for an IDE just like the one in this beautiful repository to use in our company. I've noticed that there is no licence in this repository, which means we don't feel comfortable moving forward. What is the license for this project? Could we use it for commercial purposes without paying a fee?

Thanks!

**Comment by fresh2dev** [comment]
I must've forgot about that. I'll upload the license (MIT) later.

Note that this Docker stack makes use of various other products (ShinyProxy, RStudio Server, Shiny Server, InfluxDB), each with their own licenses (though they're also open-source).

So... have fun!

**Comment by andreishappy** [comment]
Amazing, thanks for your quick answer! Will check out the licenses of the others although I don't suspect there should be any issues.

**Comment by andreishappy** [comment]
Feel free to close this issue (after you add the license of course 😉 )

**Comment by fresh2dev** [comment]
4e24fb5aa5a1c75343b5e4748ce88ba2e34aef96

Cheers,
Donald
