### ISSUE TITLE
Template customizations

### ISSUE THREAD

**Issue by jamiebono** [dm3ll3n/ShinyStudio#12]
It seems like the locations for custom page templates moved during the last update. Is there some other way to customize them?

**Comment by fresh2dev** [comment]
The template was moved here:

https://github.com/dm3ll3n/ShinyStudio-Image/tree/master/configs/shinyproxy

ShinyProxy expects the layout to be here, so you can either bind-mount the directory or copy it into the image using the Dockerfile.

`/opt/shinyproxy/templates/grid-layout`

**Comment by jamiebono** [comment]
Thank you!
