### ISSUE TITLE
Default 8080 is not accessible

### ISSUE THREAD

**Issue by yutaowang** [dm3ll3n/ShinyStudio#13]
[ec2-user@ip-172-31-1-224 ShinyStudio]$ ./control.sh start 8080
Created site config at: './configs/8080'
No HTTPS port defined; using random high-port: 53397
Creating network "shinystudio8080_default" with the default driver
Pulling influxdb (influxdb:latest)...
latest: Pulling from library/influxdb
a4d8138d0f6b: Pull complete
dbdc36973392: Pull complete
f59d6d019dd5: Pull complete
581a8bc18685: Pull complete
7cfcb592d11f: Pull complete
11ebf637f625: Pull complete
d821a8301875: Pull complete
89a24f5a36ba: Pull complete
Digest: sha256:38bc51a4a606e4c91e6adc475d28398bee05ae271102cc3e26ddbabe25cb3f71
Status: Downloaded newer image for influxdb:latest
Building shinystudio
Step 1/6 : FROM dm3ll3n/shinystudio
latest: Pulling from dm3ll3n/shinystudio
Digest: sha256:6aaa440b2403e8cc49b118f35a670830ce861f05e7999868add389daeeaf7a0f
Status: Downloaded newer image for dm3ll3n/shinystudio:latest
 ---> 05369f5c0e60
Step 2/6 : COPY configs/global/odbc/odbcinst.ini /etc/odbcinst.ini
 ---> 905370592c51
Step 3/6 : COPY configs/global/odbc/odbc.ini /etc/odbc.ini
 ---> 9a31d18507d9
Step 4/6 : COPY configs/global/krb/krb5.conf /etc/krb5.conf
 ---> b0bd638dbb86
Step 5/6 : COPY configs/global/vscode/User/settings.json /code-server-template/User/settings.json
 ---> a82898546f4c
Step 6/6 : COPY configs/global/vscode/User/snippets /code-server-template/User/snippets
 ---> e46d7074120e

Successfully built e46d7074120e
Successfully tagged shinystudio8080_shinystudio:latest
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
f5d23c7fed46: Pull complete
918b255d86e5: Pull complete
8c0120a6f561: Pull complete
Digest: sha256:eb3320e2f9ca409b7c0aa71aea3cf7ce7d018f03a372564dbdb023646958770b
Status: Downloaded newer image for nginx:latest
Creating shinystudio8080_influxdb_1 ... done
Creating shinystudio8080_shinystudio_1 ... done
Creating shinystudio8080_nginx_1       ... done
[ec2-user@ip-172-31-1-224 ShinyStudio]$
[ec2-user@ip-172-31-1-224 ShinyStudio]$
[ec2-user@ip-172-31-1-224 ShinyStudio]$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
shinystudio8080_shinystudio   latest              e46d7074120e        38 seconds ago      4.98GB
nginx                         latest              e445ab08b2be        14 hours ago        126MB
influxdb                      latest              d1e103e42e17        2 weeks ago         258MB
dm3ll3n/shinystudio           latest              05369f5c0e60        2 weeks ago         4.98GB
hello-world                   latest              fce289e99eb9        6 months ago        1.84kB
[ec2-user@ip-172-31-1-224 ShinyStudio]$ docker container ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
787b64d2ec1e        nginx                         "nginx -g 'daemon of…"   18 seconds ago      Up 17 seconds       0.0.0.0:53397->53397/tcp, 0.0.0.0:8080->80/tcp   shinystudio8080_nginx_1
6554ca0391ff        shinystudio8080_shinystudio   "/start.sh shinyproxy"   19 seconds ago      Up 18 seconds       8787/tcp                                         shinystudio8080_shinystudio_1
7529ec1602cc        influxdb                      "/entrypoint.sh infl…"   21 seconds ago      Up 19 seconds       8086/tcp                                         shinystudio8080_influxdb_1
[ec2-user@ip-172-31-1-224 ShinyStudio]$ ./control.sh start 8000
Created site config at: './configs/8000'
No HTTPS port defined; using random high-port: 59263
Creating network "shinystudio8000_default" with the default driver
Building shinystudio
Step 1/6 : FROM dm3ll3n/shinystudio
 ---> 05369f5c0e60
Step 2/6 : COPY configs/global/odbc/odbcinst.ini /etc/odbcinst.ini
 ---> Using cache
 ---> 905370592c51
Step 3/6 : COPY configs/global/odbc/odbc.ini /etc/odbc.ini
 ---> Using cache
 ---> 9a31d18507d9
Step 4/6 : COPY configs/global/krb/krb5.conf /etc/krb5.conf
 ---> Using cache
 ---> b0bd638dbb86
Step 5/6 : COPY configs/global/vscode/User/settings.json /code-server-template/User/settings.json
 ---> Using cache
 ---> a82898546f4c
Step 6/6 : COPY configs/global/vscode/User/snippets /code-server-template/User/snippets
 ---> Using cache
 ---> e46d7074120e

Successfully built e46d7074120e
Successfully tagged shinystudio8000_shinystudio:latest
Creating shinystudio8000_influxdb_1 ... done
Creating shinystudio8000_shinystudio_1 ... done
Creating shinystudio8000_nginx_1       ... done
[ec2-user@ip-172-31-1-224 ShinyStudio]$ ./control.sh start 9090
Created site config at: './configs/9090'
No HTTPS port defined; using random high-port: 52889
Creating network "shinystudio9090_default" with the default driver
Creating volume "shinystudio9090_influxdb_data" with default driver
Building shinystudio
Step 1/6 : FROM dm3ll3n/shinystudio
 ---> 05369f5c0e60
Step 2/6 : COPY configs/global/odbc/odbcinst.ini /etc/odbcinst.ini
 ---> Using cache
 ---> 905370592c51
Step 3/6 : COPY configs/global/odbc/odbc.ini /etc/odbc.ini
 ---> Using cache
 ---> 9a31d18507d9
Step 4/6 : COPY configs/global/krb/krb5.conf /etc/krb5.conf
 ---> Using cache
 ---> b0bd638dbb86
Step 5/6 : COPY configs/global/vscode/User/settings.json /code-server-template/User/settings.json
 ---> Using cache
 ---> a82898546f4c
Step 6/6 : COPY configs/global/vscode/User/snippets /code-server-template/User/snippets
 ---> Using cache
 ---> e46d7074120e

Successfully built e46d7074120e
Successfully tagged shinystudio9090_shinystudio:latest
Creating shinystudio9090_influxdb_1 ... done
Creating shinystudio9090_shinystudio_1 ... done
Creating shinystudio9090_nginx_1       ... done
[ec2-user@ip-172-31-1-224 ShinyStudio]$

**Comment by yutaowang** [comment]
./control.sh start 9090 
able to access.. 

 ./control.sh start 8000 
able to access

does nginx 8080 conflict with shinyproxy 8080 ?????

**Comment by yutaowang** [comment]
dude, you are killing me - spent hours on this..

**Comment by yutaowang** [comment]
http://ec2-52-80-125-206.cn-north-1.compute.amazonaws.com.cn:9090/ 

after click "Apps & Reports", "Documents" , whatver, all complains 500 ERROR!!! 

Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 404, body: {"message":"No such image: shinystudio_9090_shinystudio:latest"}

[ec2-user@ip-172-31-1-224 ShinyStudio]$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
shinystudio8080_shinystudio   latest              e46d7074120e        10 minutes ago      4.98GB
shinystudio9090_shinystudio   latest              e46d7074120e        10 minutes ago      4.98GB
shinystudio8000_shinystudio   latest              e46d7074120e        10 minutes ago      4.98GB
nginx                         latest              e445ab08b2be        14 hours ago        126MB
influxdb                      latest              d1e103e42e17        2 weeks ago         258MB
dm3ll3n/shinystudio           latest              05369f5c0e60        2 weeks ago         4.98GB
hello-world                   latest              fce289e99eb9        6 months ago        1.84kB

**Comment by yutaowang** [comment]
OS: Amazon Linux

**Comment by fresh2dev** [comment]
There shouldn’t be any port conflicts, as each container is its own “host” in the Docker orchestration. 

The issue likely has to do with the fact that your images are being built with an incorrect name. It appears the images were built with the name ‘shinystudio9090_...’ when it should be ‘shinystudio_9090_...’. The setup scripts should build with the proper name, but you can also follow the manual setup process in the doc to ensure the project name is correct.

-Sent from mobile

**Comment by yutaowang** [comment]
thank you so much for your quick reply and pointing to the cause. The script I used is, 

./control.sh start 9090
...
Successfully built e46d7074120e
Successfully tagged shinystudio9090_shinystudio:latest
...

I will look into the sh codes...

**Comment by yutaowang** [comment]
so wired. I am able to build correctly on my personal ubuntu laptop; but cannot get the correct REPOSITORY name on the server. I have to rename manually.

**Comment by yutaowang** [comment]
I am gonna open a new one, the title is not accurate.
