### ISSUE TITLE
Occupies entire 75gb drive on ubuntu

### ISSUE THREAD

**Issue by bpcarson** [dm3ll3n/ShinyStudio#14]
```
docker run -d --restart always --name shinyproxy \
    --network shinystudio-net \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e USERID=$USERID \
    -e USER=$USER \
    -e PASSWORD=password \
    -e CONTENT_PATH="${HOME}/ShinyStudio" \
    -e SITE_NAME=shinystudio \
    -p 8080:8080 \
    dm3ll3n/shinystudio
```

after running the docker run command above the entire disk space (75gb) is filled, preventing the application from running and results in the following error:

```
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/R/site-library/Rcpp/include/Rcpp/module/Module_generated_CppFunction.h: no space left on device.
See 'docker run --help'.

```

**Comment by fresh2dev** [comment]
The image is roughly 2GB in size. I'd recommend having at least 5GB free on your disk.

**Comment by bpcarson** [comment]
my apologies, this was on a fresh EC2 so I made the assumption it was mostly free, but it was actually nearly full even before the docker command

thanks for the quick reply!

**Comment by fresh2dev** [comment]
No prob. You had me worried! Haha; cheers.
