### ISSUE TITLE
Install: wrong version in docker-compose.yml

### ISSUE THREAD

**Issue by damienchallet** [dm3ll3n/ShinyStudio#3]
Using the following docker and docker-compose versions,

$ docker-compose --version
docker-compose version 1.17.1, build unknown
$ docker --version
Docker version 18.09.4, build d14af54266

which as I understand should support a docker-compose.yml 3.7 version, I get errors when trying to install ShinyStudio. First, a few errors that seem to originate from the fact that there is no running containers

bash ./control.sh setup
*** Stopping
"docker stop" requires at least 1 argument.
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
ERROR: Version in "./../docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
*** Building
ERROR: Version in "./../docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
*** Starting
ERROR: Version in "./../docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by fresh2dev** [comment]
For starters, you can ignore the error about there being no containers to stop. The `./control.sh setup` operation begins by stopping all pertinent containers before rebuilding and restarting the site(s). If there is nothing to stop (as is the case in the initial setup), the error will be thrown, but it can be ignored. The setup script could be made to be more robust in this way; I will address this if I get time.

Regarding the version incompatibility, is there anything preventing you from upgrading to newer versions of Docker / Docker Compose? This was designed and tested with Docker version 18.09.2, Docker compose version **1.23.2**. If you can, I suggest upgrading Docker to newer builds.

I did some testing and will be able to drop the docker-compose file version down from 3.7 to 3.5 to ensure compatibility with older Docker builds, but I cannot go lower than 3.5 without getting errors.

**Comment by damienchallet** [comment]
docker-compose's version was to be blamed, all clear now, thanks for your
work.

**Comment by fresh2dev** [comment]
Glad you got it worked out. I'll be sure to mention version requirements in the setup doc.
