### ISSUE TITLE
pushd not found

### ISSUE THREAD

**Issue by ShaulAb** [dm3ll3n/ShinyStudio#4]
Thank you very much for this!
I'm using [zsh](https://ohmyz.sh/) as default and I think that's what causing the command `./control.sh setup` to fail.
Example:
![example](https://user-images.githubusercontent.com/18129076/56132027-a682d700-5f91-11e9-8676-8db04d30535d.gif)

My solution was to add a shebang (`#!/bin/bash`) to control.sh and it worked.

**Comment by fresh2dev** [comment]
Thanks for sharing your experience. I added the shebang to the setup files in the latest commit.
